# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-29 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名称')),
                ('ipaddres', models.GenericIPAddressField(unique=True, verbose_name='ip地址')),
                ('port', models.SmallIntegerField(default=22, verbose_name='端口号')),
                ('yw', models.CharField(choices=[('app_yw', 'app业务'), ('h5_yw', 'H5业务'), ('www_yw', '官网业务')], default='app_yw', max_length=40, verbose_name='业务类型')),
                ('type_choice', models.CharField(choices=[('server', '服务器'), ('networkdevice', '网络设备'), ('storagedevice', '存储设备'), ('securitydevice', '安全设备'), ('software', '软件资产')], default='server', max_length=30, verbose_name='设备类型')),
                ('status', models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=0, verbose_name='设备状态')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('manage_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='管理用户')),
            ],
            options={
                'verbose_name': '主机列表',
                'db_table': 'addhost',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=64, unique=True, verbose_name='网站类型')),
                ('error', models.CharField(max_length=64, unique=True, verbose_name='错误个数')),
                ('success', models.CharField(max_length=64, unique=True, verbose_name='成功个数')),
                ('kind', models.CharField(max_length=64, unique=True, verbose_name='错误格式')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '爬虫统计',
                'db_table': 'spider',
                'ordering': ['-c_time'],
            },
        ),
    ]
