# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-29 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='error',
            field=models.CharField(max_length=64, verbose_name='错误个数'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='site',
            field=models.CharField(max_length=64, verbose_name='网站类型'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='success',
            field=models.CharField(max_length=64, verbose_name='成功个数'),
        ),
    ]
