# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-29 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190829_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ipaddres',
            field=models.GenericIPAddressField(unique=True, verbose_name=b'ip\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AlterField(
            model_name='host',
            name='manage_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86\xe7\x94\xa8\xe6\x88\xb7'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8'),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.SmallIntegerField(default=22, verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.SmallIntegerField(choices=[(0, b'\xe5\x9c\xa8\xe7\xba\xbf'), (1, b'\xe4\xb8\x8b\xe7\xba\xbf'), (2, b'\xe6\x9c\xaa\xe7\x9f\xa5'), (3, b'\xe6\x95\x85\xe9\x9a\x9c'), (4, b'\xe5\xa4\x87\xe7\x94\xa8')], default=0, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='host',
            name='type_choice',
            field=models.CharField(choices=[(b'server', b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (b'networkdevice', b'\xe7\xbd\x91\xe7\xbb\x9c\xe8\xae\xbe\xe5\xa4\x87'), (b'storagedevice', b'\xe5\xad\x98\xe5\x82\xa8\xe8\xae\xbe\xe5\xa4\x87'), (b'securitydevice', b'\xe5\xae\x89\xe5\x85\xa8\xe8\xae\xbe\xe5\xa4\x87'), (b'software', b'\xe8\xbd\xaf\xe4\xbb\xb6\xe8\xb5\x84\xe4\xba\xa7')], default=b'server', max_length=30, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='yw',
            field=models.CharField(choices=[(b'app_yw', b'app\xe4\xb8\x9a\xe5\x8a\xa1'), (b'h5_yw', b'H5\xe4\xb8\x9a\xe5\x8a\xa1'), (b'www_yw', b'\xe5\xae\x98\xe7\xbd\x91\xe4\xb8\x9a\xe5\x8a\xa1')], default=b'app_yw', max_length=40, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='c_time',
            field=models.CharField(max_length=64, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='error',
            field=models.CharField(max_length=64, verbose_name=b'\xe9\x94\x99\xe8\xaf\xaf\xe4\xb8\xaa\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='site',
            field=models.CharField(max_length=64, verbose_name=b'\xe7\xbd\x91\xe7\xab\x99\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='success',
            field=models.CharField(max_length=64, verbose_name=b'\xe6\x88\x90\xe5\x8a\x9f\xe4\xb8\xaa\xe6\x95\xb0'),
        ),
    ]
