# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-05 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20190829_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, verbose_name='主机名称'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ipaddres',
            field=models.GenericIPAddressField(unique=True, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='manage_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='管理用户'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.SmallIntegerField(default=22, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=0, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='host',
            name='type_choice',
            field=models.CharField(choices=[('server', '服务器'), ('networkdevice', '网络设备'), ('storagedevice', '存储设备'), ('securitydevice', '安全设备'), ('software', '软件资产')], default='server', max_length=30, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='yw',
            field=models.CharField(choices=[('app_yw', 'app业务'), ('h5_yw', 'H5业务'), ('www_yw', '官网业务')], default='app_yw', max_length=40, verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='c_time',
            field=models.DateField(max_length=64, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='error',
            field=models.CharField(max_length=64, verbose_name='错误个数'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='site',
            field=models.CharField(max_length=64, verbose_name='网站类型'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='success',
            field=models.CharField(max_length=64, verbose_name='成功个数'),
        ),
    ]
