# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20190617_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='spider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=64, unique=True, verbose_name=b'\xe7\xbd\x91\xe7\xab\x99\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('error', models.CharField(max_length=64, unique=True, verbose_name=b'\xe9\x94\x99\xe8\xaf\xaf\xe4\xb8\xaa\xe6\x95\xb0')),
                ('success', models.CharField(max_length=64, unique=True, verbose_name=b'\xe6\x88\x90\xe5\x8a\x9f\xe4\xb8\xaa\xe6\x95\xb0')),
                ('kind', models.CharField(max_length=64, unique=True, verbose_name=b'\xe9\x94\x99\xe8\xaf\xaf\xe6\xa0\xbc\xe5\xbc\x8f')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'ordering': ['-c_time'],
                'db_table': 'spider',
                'verbose_name': '\u722c\u866b\u7edf\u8ba1',
            },
        ),
    ]
