result=[
    {
        "title":"www",
        "success_legend":[
            "baidu_success",
            "360_success",
            "sougo_success",
            "yisou_success"
        ],
        "error_legend":[
            "baidu_error",
            "360_error",
            "sougo_error",
            "yisou_error"
        ],
        "success_data":[
            {
                "name":"baidu_success",
                "data":[
                    "187964",
                    "190942",
                    "206347",
                    "181193",
                    "214833"
                ]
            },
            {
                "name":"360_success",
                "data":[
                    "155581",
                    "161024",
                    "67686",
                    "98564",
                    "84350"
                ]
            },
            {
                "name":"sougo_success",
                "data":[
                    "1934363",
                    "1308011",
                    "1000961",
                    "1625001",
                    "1645267"
                ]
            },
            {
                "name":"yisou_success",
                "data":[
                    "265846",
                    "274363",
                    "278910",
                    "277764",
                    "264552"
                ]
            }
        ],
        "error_data":[
            {
                "name":"baidu_error",
                "data":[
                    "10144",
                    "8759",
                    "13574",
                    "9881",
                    "21235"
                ]
            },
            {
                "name":"360_error",
                "data":[
                    "3260",
                    "1875",
                    "980",
                    "835",
                    "2876"
                ]
            },
            {
                "name":"sougo_error",
                "data":[
                    "21624",
                    "10871",
                    "13968",
                    "10420",
                    "26344"
                ]
            },
            {
                "name":"yisou_error",
                "data":[
                    "27109",
                    "22481",
                    "24757",
                    "23607",
                    "15082"
                ]
            }
        ],
        "time":[
            "2019-08-28",
            "2019-08-27",
            "2019-08-26",
            "2019-08-25",
            "2019-08-24"
        ]
    },
    {
        "title":"m",
        "success_legend":[
            "baidu_success",
            "360_success",
            "sougo_success",
            "yisou_success"
        ],
        "error_legend":[
            "baidu_error",
            "360_error",
            "sougo_error",
            "yisou_error"
        ],
        "success_data":[
            {
                "name":"baidu_success",
                "data":[
                    "263897",
                    "240982",
                    "288040",
                    "275376",
                    "262098"
                ]
            },
            {
                "name":"360_success",
                "data":[
                    "726",
                    "859",
                    "1044",
                    "1108",
                    "738"
                ]
            },
            {
                "name":"sougo_success",
                "data":[
                    "42902",
                    "42539",
                    "40402",
                    "37043",
                    "36879"
                ]
            },
            {
                "name":"yisou_success",
                "data":[
                    "275571",
                    "172346",
                    "235542",
                    "266645",
                    "187093"
                ]
            }
        ],
        "error_data":[
            {
                "name":"baidu_error",
                "data":[
                    "8646",
                    "6698",
                    "6818",
                    "8046",
                    "8733"
                ]
            },
            {
                "name":"360_error",
                "data":[
                    "24",
                    "12",
                    "14",
                    "15",
                    "19"
                ]
            },
            {
                "name":"sougo_error",
                "data":[
                    "2569",
                    "1728",
                    "2428",
                    "2007",
                    "1591"
                ]
            },
            {
                "name":"yisou_error",
                "data":[
                    "11009",
                    "6497",
                    "8359",
                    "10685",
                    "9120"
                ]
            }
        ],
        "time":[
            "2019-08-28",
            "2019-08-27",
            "2019-08-26",
            "2019-08-25",
            "2019-08-24"
        ]
    }
]

# test= 'name':'邮件营销',
#             'type':'line',
#             'stack': '总量',
#             'data':[120, 132, 101, 134, 90, 230, 210]

w=result[0]
m=result[1]









